spring:
  cloud:
    gateway:
      routes:
        - id: uuid_route
          uri: http://httpbin:80
          predicates:
            - Path=/uuidRoute
          filters:
            - AddUuidRequestHeader=My-Session-Id
            - RewritePath=/uuidRoute, /anything

        - id: external_call_route
          uri: http://httpbin:80
          predicates:
            - Path=/externalRoute
          filters:
            - CallExternalService
            - RewritePath=/externalRoute, /anything

externalService:
  connectTimeoutMs: 250
  readTimeoutMs: 500
  writeTimeoutMs: 500
  uri: http://wiremock:8080