version: '3.8'
services:

  # Builds and deploys my spring-cloud-gateway
  scg:
    build: .
    ports:
      - 8080:8080
      - 5005:5005

  # Deploys an httpbin instance
  httpbin:
    image: kennethreitz/httpbin:latest
    ports:
      - 8081:80

  # Deploys a wiremock instance
  wiremock:
    image: rodolpheche/wiremock:latest
    volumes:
      - ./stubs:/home/wiremock
    ports:
      - 8082:8080