version: '3.8'
services:

  # Builds and deploys my spring-cloud-gateway
  scg:
    build: .
    environment:
      ENABLE_DEBUG: 'true'
    ports:
      - 8080:8080
      - 5005:5005
    volumes:
      - ./my-config:/srv/gateway/config

  # Deploys an httpbin instance
  httpbin:
    image: kennethreitz/httpbin:latest
    ports:
      - 8081:80

  # Deploys a wiremock instance
  wiremock:
    image: rodolpheche/wiremock:latest
    ports:
      - 8082:8080
    volumes:
      - ./stubs:/home/wiremock